version: "3.3"

services:
  pg:
    image: postgres:10.7
    environment:
      POSTGRES_DB: database_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  pg_data: